name: Push in PR into develop branch. Ruff checks and App tests.

on:
  pull_request:
    branches:
      - develop

jobs:
  ruff_checks:
    name: Ruff Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.16"

      - name: Set Up Python
        run: uv python install

      - name: Ruff and mypy Checks
        run: make ruff_check && make mypy_check

  app_tests:
    name: App Tests
    runs-on: ubuntu-latest
    needs: ruff_checks
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Tests in Docker Containers
        run: |
          make test