name: Push in PR into main branch. Ruff checks and App tests.

on:
  pull_request:
    branches:
      - main

jobs:
  ruff_checks:
    name: Ruff Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.16"

      - name: Set Up Python
        run: uv python install

      - name: Ruff Checks
        run: uvx ruff@0.12.4 check . && uvx ruff@0.12.4 check --select I . && uvx ruff@0.12.4 format --check .

  app_tests:
    name: App Tests
    runs-on: ubuntu-latest
    needs: ruff_checks
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Tests in Docker Containers
        run: |
          make test